import SwiftUI
import SipTrackKit

/// ContentView — thin SwiftUI shell that hosts the Compose Multiplatform UI.
/// All business logic and UI live in the shared Kotlin/Compose layer.
struct ContentView: View {
    var body: some View {
        ComposeView()
            .ignoresSafeArea(.all, edges: .all)
    }
}

/// UIViewControllerRepresentable that bridges SwiftUI with Compose Multiplatform.
struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        // MainViewControllerKt.MainViewController() is generated by KMP
        // from composeApp/src/iosMain/kotlin/MainViewController.kt
        MainViewControllerKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}

#Preview {
    ContentView()
}
